### ISSUE TITLE
Open source?

### ISSUE THREAD

**Issue by beporter** [loadsys/code-retreat-tools#1]
Any chance this repo can be made not-private? I'm not sure if I _should_ or not, but somehow I'm able to still see this, and I have Admin access, so I can do it myself I guess...

cc: @justinyost

**Comment by justinyost** [comment]
Asking around @beporter

**Comment by leeforkenbrock** [comment]
Sorry, I tried responding via email, but I guess that doesn't work with GitHub.  I am ok with it as long as there is nothing proprietary or client related.

**Comment by justinyost** [comment]
Repo is now public.

**Comment by leeforkenbrock** [comment]
I don't mind as long as there is nothing proprietary.
